name: sore_beta_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  pdf: ^3.10.1

  share_extend: ^2.0.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.5.0
  firebase_storage: ^11.0.11
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.3.2
  fluttertoast: ^8.1.3
  firebase_database: ^10.0.10
  image_picker: ^0.8.6+1
  carousel_slider: ^4.2.1
  ndialog: ^4.3.0
  barcode_widget: ^2.0.3
  intl: ^0.17.0
  path_provider: ^2.0.5
  flutter_barcode_scanner: ^2.0.0
  uuid: ^3.0.6
  video_player: ^2.6.1
  google_fonts: ^4.0.3
  excel: 2.1.0
  flutter_datetime_picker: ^1.5.1
  syncfusion_flutter_charts: ^21.1.41



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.0"

flutter_icons:
  android: true
  image_path_android: "assets/launcher/icon.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
          style: normal
    - family: Times
      fonts:
        - asset: assets/fonts/Times-New-Roman.ttf
          style: normal
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf



  assets:
    - assets/images/
    - assets/launcher/



